/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as WSlugRouteImport } from './routes/w.$slug'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard.admin.index'
import { Route as DashboardProjectsNewRouteImport } from './routes/dashboard.projects.new'
import { Route as DashboardProjectsIdRouteImport } from './routes/dashboard.projects.$id'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard.admin.users'
import { Route as DashboardAdminProjectsRouteImport } from './routes/dashboard.admin.projects'
import { Route as DashboardProjectsIdIndexRouteImport } from './routes/dashboard.projects.$id.index'
import { Route as DashboardProjectsIdWidgetRouteImport } from './routes/dashboard.projects.$id.widget'
import { Route as DashboardProjectsIdWebhooksRouteImport } from './routes/dashboard.projects.$id.webhooks'
import { Route as DashboardProjectsIdSubscribersRouteImport } from './routes/dashboard.projects.$id.subscribers'
import { Route as DashboardProjectsIdSmtpRouteImport } from './routes/dashboard.projects.$id.smtp'
import { Route as DashboardProjectsIdSettingsRouteImport } from './routes/dashboard.projects.$id.settings'
import { Route as DashboardProjectsIdEmailsRouteImport } from './routes/dashboard.projects.$id.emails'
import { Route as DashboardProjectsIdApiKeysRouteImport } from './routes/dashboard.projects.$id.api-keys'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const WSlugRoute = WSlugRouteImport.update({
  id: '/w/$slug',
  path: '/w/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardProjectsNewRoute = DashboardProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsIdRoute = DashboardProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminProjectsRoute = DashboardAdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardProjectsIdIndexRoute =
  DashboardProjectsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProjectsIdRoute,
  } as any)
const DashboardProjectsIdWidgetRoute =
  DashboardProjectsIdWidgetRouteImport.update({
    id: '/widget',
    path: '/widget',
    getParentRoute: () => DashboardProjectsIdRoute,
  } as any)
const DashboardProjectsIdWebhooksRoute =
  DashboardProjectsIdWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => DashboardProjectsIdRoute,
  } as any)
const DashboardProjectsIdSubscribersRoute =
  DashboardProjectsIdSubscribersRouteImport.update({
    id: '/subscribers',
    path: '/subscribers',
    getParentRoute: () => DashboardProjectsIdRoute,
  } as any)
const DashboardProjectsIdSmtpRoute = DashboardProjectsIdSmtpRouteImport.update({
  id: '/smtp',
  path: '/smtp',
  getParentRoute: () => DashboardProjectsIdRoute,
} as any)
const DashboardProjectsIdSettingsRoute =
  DashboardProjectsIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardProjectsIdRoute,
  } as any)
const DashboardProjectsIdEmailsRoute =
  DashboardProjectsIdEmailsRouteImport.update({
    id: '/emails',
    path: '/emails',
    getParentRoute: () => DashboardProjectsIdRoute,
  } as any)
const DashboardProjectsIdApiKeysRoute =
  DashboardProjectsIdApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => DashboardProjectsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/w/$slug': typeof WSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/projects': typeof DashboardAdminProjectsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRouteWithChildren
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/projects/$id/api-keys': typeof DashboardProjectsIdApiKeysRoute
  '/dashboard/projects/$id/emails': typeof DashboardProjectsIdEmailsRoute
  '/dashboard/projects/$id/settings': typeof DashboardProjectsIdSettingsRoute
  '/dashboard/projects/$id/smtp': typeof DashboardProjectsIdSmtpRoute
  '/dashboard/projects/$id/subscribers': typeof DashboardProjectsIdSubscribersRoute
  '/dashboard/projects/$id/webhooks': typeof DashboardProjectsIdWebhooksRoute
  '/dashboard/projects/$id/widget': typeof DashboardProjectsIdWidgetRoute
  '/dashboard/projects/$id/': typeof DashboardProjectsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/w/$slug': typeof WSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/projects': typeof DashboardAdminProjectsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/projects/$id/api-keys': typeof DashboardProjectsIdApiKeysRoute
  '/dashboard/projects/$id/emails': typeof DashboardProjectsIdEmailsRoute
  '/dashboard/projects/$id/settings': typeof DashboardProjectsIdSettingsRoute
  '/dashboard/projects/$id/smtp': typeof DashboardProjectsIdSmtpRoute
  '/dashboard/projects/$id/subscribers': typeof DashboardProjectsIdSubscribersRoute
  '/dashboard/projects/$id/webhooks': typeof DashboardProjectsIdWebhooksRoute
  '/dashboard/projects/$id/widget': typeof DashboardProjectsIdWidgetRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/w/$slug': typeof WSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/projects': typeof DashboardAdminProjectsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRouteWithChildren
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/projects/$id/api-keys': typeof DashboardProjectsIdApiKeysRoute
  '/dashboard/projects/$id/emails': typeof DashboardProjectsIdEmailsRoute
  '/dashboard/projects/$id/settings': typeof DashboardProjectsIdSettingsRoute
  '/dashboard/projects/$id/smtp': typeof DashboardProjectsIdSmtpRoute
  '/dashboard/projects/$id/subscribers': typeof DashboardProjectsIdSubscribersRoute
  '/dashboard/projects/$id/webhooks': typeof DashboardProjectsIdWebhooksRoute
  '/dashboard/projects/$id/widget': typeof DashboardProjectsIdWidgetRoute
  '/dashboard/projects/$id/': typeof DashboardProjectsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/docs'
    | '/login'
    | '/privacy-policy'
    | '/register'
    | '/reset-password'
    | '/dashboard/admin'
    | '/dashboard/settings'
    | '/w/$slug'
    | '/dashboard/'
    | '/dashboard/admin/projects'
    | '/dashboard/admin/users'
    | '/dashboard/projects/$id'
    | '/dashboard/projects/new'
    | '/dashboard/admin/'
    | '/dashboard/projects/$id/api-keys'
    | '/dashboard/projects/$id/emails'
    | '/dashboard/projects/$id/settings'
    | '/dashboard/projects/$id/smtp'
    | '/dashboard/projects/$id/subscribers'
    | '/dashboard/projects/$id/webhooks'
    | '/dashboard/projects/$id/widget'
    | '/dashboard/projects/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/docs'
    | '/login'
    | '/privacy-policy'
    | '/register'
    | '/reset-password'
    | '/dashboard/settings'
    | '/w/$slug'
    | '/dashboard'
    | '/dashboard/admin/projects'
    | '/dashboard/admin/users'
    | '/dashboard/projects/new'
    | '/dashboard/admin'
    | '/dashboard/projects/$id/api-keys'
    | '/dashboard/projects/$id/emails'
    | '/dashboard/projects/$id/settings'
    | '/dashboard/projects/$id/smtp'
    | '/dashboard/projects/$id/subscribers'
    | '/dashboard/projects/$id/webhooks'
    | '/dashboard/projects/$id/widget'
    | '/dashboard/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/docs'
    | '/login'
    | '/privacy-policy'
    | '/register'
    | '/reset-password'
    | '/dashboard/admin'
    | '/dashboard/settings'
    | '/w/$slug'
    | '/dashboard/'
    | '/dashboard/admin/projects'
    | '/dashboard/admin/users'
    | '/dashboard/projects/$id'
    | '/dashboard/projects/new'
    | '/dashboard/admin/'
    | '/dashboard/projects/$id/api-keys'
    | '/dashboard/projects/$id/emails'
    | '/dashboard/projects/$id/settings'
    | '/dashboard/projects/$id/smtp'
    | '/dashboard/projects/$id/subscribers'
    | '/dashboard/projects/$id/webhooks'
    | '/dashboard/projects/$id/widget'
    | '/dashboard/projects/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DocsRoute: typeof DocsRoute
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WSlugRoute: typeof WSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/w/$slug': {
      id: '/w/$slug'
      path: '/w/$slug'
      fullPath: '/w/$slug'
      preLoaderRoute: typeof WSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/projects/new': {
      id: '/dashboard/projects/new'
      path: '/projects/new'
      fullPath: '/dashboard/projects/new'
      preLoaderRoute: typeof DashboardProjectsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/$id': {
      id: '/dashboard/projects/$id'
      path: '/projects/$id'
      fullPath: '/dashboard/projects/$id'
      preLoaderRoute: typeof DashboardProjectsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/projects': {
      id: '/dashboard/admin/projects'
      path: '/projects'
      fullPath: '/dashboard/admin/projects'
      preLoaderRoute: typeof DashboardAdminProjectsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/projects/$id/': {
      id: '/dashboard/projects/$id/'
      path: '/'
      fullPath: '/dashboard/projects/$id/'
      preLoaderRoute: typeof DashboardProjectsIdIndexRouteImport
      parentRoute: typeof DashboardProjectsIdRoute
    }
    '/dashboard/projects/$id/widget': {
      id: '/dashboard/projects/$id/widget'
      path: '/widget'
      fullPath: '/dashboard/projects/$id/widget'
      preLoaderRoute: typeof DashboardProjectsIdWidgetRouteImport
      parentRoute: typeof DashboardProjectsIdRoute
    }
    '/dashboard/projects/$id/webhooks': {
      id: '/dashboard/projects/$id/webhooks'
      path: '/webhooks'
      fullPath: '/dashboard/projects/$id/webhooks'
      preLoaderRoute: typeof DashboardProjectsIdWebhooksRouteImport
      parentRoute: typeof DashboardProjectsIdRoute
    }
    '/dashboard/projects/$id/subscribers': {
      id: '/dashboard/projects/$id/subscribers'
      path: '/subscribers'
      fullPath: '/dashboard/projects/$id/subscribers'
      preLoaderRoute: typeof DashboardProjectsIdSubscribersRouteImport
      parentRoute: typeof DashboardProjectsIdRoute
    }
    '/dashboard/projects/$id/smtp': {
      id: '/dashboard/projects/$id/smtp'
      path: '/smtp'
      fullPath: '/dashboard/projects/$id/smtp'
      preLoaderRoute: typeof DashboardProjectsIdSmtpRouteImport
      parentRoute: typeof DashboardProjectsIdRoute
    }
    '/dashboard/projects/$id/settings': {
      id: '/dashboard/projects/$id/settings'
      path: '/settings'
      fullPath: '/dashboard/projects/$id/settings'
      preLoaderRoute: typeof DashboardProjectsIdSettingsRouteImport
      parentRoute: typeof DashboardProjectsIdRoute
    }
    '/dashboard/projects/$id/emails': {
      id: '/dashboard/projects/$id/emails'
      path: '/emails'
      fullPath: '/dashboard/projects/$id/emails'
      preLoaderRoute: typeof DashboardProjectsIdEmailsRouteImport
      parentRoute: typeof DashboardProjectsIdRoute
    }
    '/dashboard/projects/$id/api-keys': {
      id: '/dashboard/projects/$id/api-keys'
      path: '/api-keys'
      fullPath: '/dashboard/projects/$id/api-keys'
      preLoaderRoute: typeof DashboardProjectsIdApiKeysRouteImport
      parentRoute: typeof DashboardProjectsIdRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminProjectsRoute: typeof DashboardAdminProjectsRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminProjectsRoute: DashboardAdminProjectsRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardProjectsIdRouteChildren {
  DashboardProjectsIdApiKeysRoute: typeof DashboardProjectsIdApiKeysRoute
  DashboardProjectsIdEmailsRoute: typeof DashboardProjectsIdEmailsRoute
  DashboardProjectsIdSettingsRoute: typeof DashboardProjectsIdSettingsRoute
  DashboardProjectsIdSmtpRoute: typeof DashboardProjectsIdSmtpRoute
  DashboardProjectsIdSubscribersRoute: typeof DashboardProjectsIdSubscribersRoute
  DashboardProjectsIdWebhooksRoute: typeof DashboardProjectsIdWebhooksRoute
  DashboardProjectsIdWidgetRoute: typeof DashboardProjectsIdWidgetRoute
  DashboardProjectsIdIndexRoute: typeof DashboardProjectsIdIndexRoute
}

const DashboardProjectsIdRouteChildren: DashboardProjectsIdRouteChildren = {
  DashboardProjectsIdApiKeysRoute: DashboardProjectsIdApiKeysRoute,
  DashboardProjectsIdEmailsRoute: DashboardProjectsIdEmailsRoute,
  DashboardProjectsIdSettingsRoute: DashboardProjectsIdSettingsRoute,
  DashboardProjectsIdSmtpRoute: DashboardProjectsIdSmtpRoute,
  DashboardProjectsIdSubscribersRoute: DashboardProjectsIdSubscribersRoute,
  DashboardProjectsIdWebhooksRoute: DashboardProjectsIdWebhooksRoute,
  DashboardProjectsIdWidgetRoute: DashboardProjectsIdWidgetRoute,
  DashboardProjectsIdIndexRoute: DashboardProjectsIdIndexRoute,
}

const DashboardProjectsIdRouteWithChildren =
  DashboardProjectsIdRoute._addFileChildren(DashboardProjectsIdRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProjectsIdRoute: typeof DashboardProjectsIdRouteWithChildren
  DashboardProjectsNewRoute: typeof DashboardProjectsNewRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProjectsIdRoute: DashboardProjectsIdRouteWithChildren,
  DashboardProjectsNewRoute: DashboardProjectsNewRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DocsRoute: DocsRoute,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WSlugRoute: WSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
